apiVersion: v1
kind: Service
metadata: 
  name: python-flask-service
spec: 
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30127
  selector: 
    app: flask-webapp
  type: NodePort
   