apiVersion: v1
kind: Service
metadata: 
  name: init-container-service
spec: 
  selector: 
    app: init-container
  ports: 
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30009
  type: NodePort  