apiVersion: v1
kind: Service
metadata: 
  name: init-service
spec:
  type: NodePort
  selector:
    app: simpleapp-webapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31255
    name: http
    protocol: "TCP"