apiVersion: batch/v1
kind: CronJob
metadata: 
  name: test-cronjob
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers: 
          - name: test-container
            image: alpine
            command: ["/bin/sh","-c"]
            args: ["echo todays date is `date`"]
          restartPolicy: OnFailure