apiVersion: batch/v1
kind: Job
metadata: 
  name: test-job
spec:
  template:
    metadata:
      name: test-job-pod
    spec:
      containers: 
      - name: test-container
        image: alpine
        command: ["/bin/sh","-c"]
        args: ["echo todays date is `date`"]
      restartPolicy: OnFailure